### ISSUE TITLE
Dialog not positioned correctly if parent has transform: scale(x)

### ISSUE THREAD

**Issue by Bulan** [PolymerElements/paper-dialog#105]
### Description

If the parent element has `style="transform:scale(x)"` the dialog end up behind the overlay and can't be interacted with.
### Expected outcome

Dialog should behave as normal.
### Actual outcome

Non-interactable dialog is shown.
### Live Demo

http://jsbin.com/namefinolu/edit?html,output
### Steps to reproduce

Add a a dialog to an element with the `style="transform:scale(1)"` set.
### Browsers Affected

Only checked in Chrome

**Comment by valdrinkoshi** [comment]
Hi @Bulan, this problem is caused by the way [stacking context](https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Positioning/Understanding_z_index/The_stacking_context) works (see [this example](http://jsbin.com/lemufe/4/edit?html,output)), and has already been reported before (see this [similar issue](https://github.com/PolymerElements/paper-dialog/issues/101)).
Appending the backdrop as a sibling of the dialog is not a viable solution because it might break the styles and it won't completely solve the issue (the dialog & backdrop could be cropped if there is a cropping stacking context containing them).
As mentioned in the [iron-overlay-behavior documentation](https://elements.polymer-project.org/elements/iron-overlay-behavior):

> You must ensure no element has a stacking context with a higher z-index than its parent stacking context. You should place this element as a child of &lt;body&gt; whenever possible.

I'm working on [this PR](https://github.com/PolymerElements/iron-overlay-behavior/pull/155) to provide helpers for this particular issue, and it basically consists in stamping overlays in the Right Place ™
