### ISSUE TITLE
Modal Dialog embed in another custom element appear under the overlay

### ISSUE THREAD

**Issue by cbalit** [PolymerElements/paper-dialog#109]
Maybe i missed something but if i try to put a modal paper-dialog in another component, i can see the overlay over the modal. 
The overlay is add to the document.body with a z-index of 102. 
The paper-dialog has a z-index to 103 but because it is add inside another component, it still appear under the overlay. This is coherent but i wonder how i can use a modal dialog inside a custom element.

**Comment by valdrinkoshi** [comment]
Hi @cbalit, the `iron-overlay-backdrop` is added to `body` (the one with z-index 102), and its job is to prevent interactions with the rest of the ui, just with the overlay (in your case `paper-dialog`).
If you are not able to interact with the `paper-dialog` because the `iron-overlay-backdrop` is on top of it, it means you inserted the `paper-dialog` inside an element that creates a new [stacking context](https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Positioning/Understanding_z_index/The_stacking_context), something [like this](http://jsbin.com/lemufe/4/edit?html,output).
This is a known limitation mentioned in the [iron-overlay-behavior documentation](https://elements.polymer-project.org/elements/iron-overlay-behavior):

> You must ensure no element has a stacking context with a higher z-index than its parent stacking context. You should place this element as a child of &lt;body&gt; whenever possible.

**Comment by cbalit** [comment]
Hi @valdrinkoshi and thank's for the response. I miss the know limitation in the documentation. I close the issue.
