### ISSUE TITLE
vertical align is not working as expected

### ISSUE THREAD

**Issue by motss** [PolymerElements/paper-dialog#115]
### Description

`vertical-align="bottom"` does not position the `paper-dialog` to the bottom of the screen.
### Expected outcome

The following code correctly positions the dialog the to bottom right of the screen.

```
  <paper-dialog horizontal-align="right" vertical-align="bottom"> ... </paper-dialog>
```
### Actual outcome

`vertical-align` has the same outcome regardless of the value being applied as the dialog always at the top of the screen.
### Live Demo

http://jsbin.com/qulohagalo/edit?html,output
### Browsers Affected

- [x] Chrome
- [ ] Firefox
- [ ] Safari 9
- [ ] Safari 8
- [ ] Safari 7
- [ ] Edge
- [ ] IE 11
- [ ] IE 10

**Comment by valdrinkoshi** [comment]
The position depends on the `positionTarget`, which defaults to the parent element (in your example, to `x-example`).
If you set it to be `window`, it will position as you expect http://jsbin.com/cogise/2/edit?html,output

**Comment by motss** [comment]
@valdrinkoshi Thanks for the clarification. It worked! Is there any problem to always set the `positionTarget` of the `paper-dialog` to `window`? Then why it defaults to the parent element instead?

**Comment by valdrinkoshi** [comment]
`positionTarget` is a property of `iron-fit-behavior`. This behavior can be used also for non-overlays, and the default position target is usually the parent of the element. This was a property of `iron-dropdown`, then moved to `iron-fit-behavior` so that all overlays could benefit from it. `iron-dropdown` in particular checks who's the parent to position itself.
Hope this makes sense :)

**Comment by motss** [comment]
@valdrinkoshi Just notice any issue. The dialog has different value of CSS `left`. The `paper-dialog` has a much smaller value of CSS `left` an emulated Nexus 5X on Chrome than on a desktop/ wide layout. On desktop mode, larger value of CSS `left` renders the `paper-dialog` to become smaller. The difference can also be seen when `horizontal-align` is different. `horizontal-align="right"` has a larger CSS `left`.

**Comment by valdrinkoshi** [comment]
uhm, maybe because of how `window` is sized in the cases you describe...very weird O_o
Have you tried with setting either `document`, or `document.documentElement` (the html tag), or `document.body`? The latter might not be a valid option if `body` is scrollable. 
Update: it is expected to have a bigger/smaller value of `left` according to the screen size, since you want to align the dialog on the right. I see it positioned on the right spot
![nexus5x](https://cloud.githubusercontent.com/assets/6173664/16386157/e159c348-3c8f-11e6-91e8-6ec91c86aee3.gif)

**Comment by motss** [comment]
@valdrinkoshi It was caused by the scrollbar. Without scrollbar, everything is normal. When the page has document scrollbar and `positionTarget` is `window`, the `paper-dialog` has larger CSS `left` thus making the overlay to have smaller width. Is this the expected behavior?

**Comment by valdrinkoshi** [comment]
Uhm yeah it makes sense to me, these adjustments are computed by `iron-fit-behavior` to ensure the element is on screen and doesn't get cropped. It fits the element so it fits inside `fitInto` (which is `window`), and positions it according to `vertical/horizontalAlign` and `positionTarget`. It respects the margin value too.
From the tests I did, I see it behaving correctly:
![nexus5x](https://cloud.githubusercontent.com/assets/6173664/16386426/06207a04-3c91-11e6-96f4-41caac24909b.gif)

**Comment by motss** [comment]
@valdrinkoshi On desktop mode, the scrollbar is relatively larger like around 16px wide. The third list item `Print this page` will become 2 lines. My workaround is to remove the scrollbar using `document.body.style.overflow = 'hidden';` before opening the overlay.

**Comment by valdrinkoshi** [comment]
Oh I see. Yeah, `window` size won't include the scrollbar :/

**Comment by valdrinkoshi** [comment]
It is a valid option to position the dialog yourself too, via css (after all, you want it positioned to the window bottom-right):

``` css
.myDialog {
  position: fixed;
  bottom: 10px;
  right: 10px;
}
```

http://jsbin.com/cogise/4/edit?html,output
`horizontal/verticalAlign` turn to be more useful when you need to position according to another element.

**Comment by motss** [comment]
@valdrinkoshi This works the best so far. Thank you.
