### ISSUE TITLE
Cannot reopen

### ISSUE THREAD

**Issue by maca** [PolymerElements/paper-dialog#12]
I can open the paper-dialog by setting the opened property to `true` but the dialog wont open again:

```
<dom-module id="x-modal-session-info">
  <template>
    <paper-dialog modal opened="{{opened}}">
      ....
      <div class="buttons">
       ...
      </div>
    </paper-dialog>
  </template>
</dom-module>

  <dom-module id="x-modal-close-session">
    <template>
      <template is="dom-if" if="{{hasTrackedTime}}">
        <x-modal-session-info tracker="{{tracker}}" opened={{opened}}>
        </x-modal-session-info>
      </template>

      <template is="dom-if" if="{{!hasTrackedTime}}">
        <x-modal-session-not-tracked opened="{{opened}}">
        </x-modal-session-not-tracked>
      </template>
    </template>
  </dom-module>

 <script>
  Polymer({
    is: "x-modal-close-session",
    open: function() {
      this.set('opened', true);
    }
    ...
  </script>
```

**Comment by zakpatterson** [comment]
I ran into the same issue with this one.  If you give your paper-dialog an id, and call `this.$.dialogId.open()`, and `this.$.dialogId.close()` instead of just setting opened to true/false, then it will work.  I also noticed this is the only way it is done in the demo:

https://elements.polymer-project.org/elements/paper-dialog?view=demo:demo/index.html

I think it's a bug in the observer of iron-overlay-behavior, but I'm not sure...

https://github.com/PolymerElements/iron-overlay-behavior/blob/master/iron-overlay-behavior.html#L225

**Comment by morethanreal** [comment]
@maca It looks like you want to two-way bind `x-modal-session-info`'s `opened` property to `x-modal-close-session`'s `opened` property. `x-modal-session-info` needs to declare `opened` with `notify:true` in its property block for it to work.

Example: https://github.com/morethanreal/paper-dialog-12/blob/master/x-modal-session-info.html#L28
