### ISSUE TITLE
Modal dialogs inside header panel on ios browser does not work 

### ISSUE THREAD

**Issue by blasten** [PolymerElements/paper-dialog#23]
Moved from https://github.com/PolymerElements/paper-header-panel/issues/33

This simple markup works fine on chome,firefox and MacOS safari, but place the dialog under the backdrop layer on IOS safari browser.

```
          <paper-header-panel fit>
            <paper-toolbar>
              <paper-icon-button icon="menu"></paper-icon-button>
              <div>Title</div>
            </paper-toolbar>
            <div fit>
              <paper-dialog id="picker" modal>
                <h2>Dialog Title</h2>
                <p>Lorem ipsum dolor</p>
                <div class="buttons">
                  <paper-button >More Info...</paper-button>
                  <paper-button dialog-dismiss>Decline</paper-button>
                  <paper-button dialog-confirm autofocus>Accept</paper-button>
                </div>
              </paper-dialog>

              <paper-button on-click="doClick">OK</paper-button>
            </div>
          </paper-header-panel>

```

Screenshot is here https://goo.gl/photos/QNqBem5JFNfZbeZC7

**Comment by kenjitayama** [comment]
I'm experiencing this too, and `paper-dialog { z-index: 10000; }` did not help.

**Comment by firasdib** [comment]
Status on this?

**Comment by kenjitayama** [comment]
Occured in iOS 9 too (Mobile Safari and UIWebView).

**Comment by ronnyroeller** [comment]
+1

**Comment by Avenel** [comment]
+1

**Comment by valdrinkoshi** [comment]
Tested on emulator and could not reproduce http://jsbin.com/hidono/3/edit?html,output
![dialog-and-header](https://cloud.githubusercontent.com/assets/6173664/11674333/b09cb5c6-9dd4-11e5-9641-4dee5150faa4.gif)

**Comment by marxtseng** [comment]
+1
Tested on emulator and ios device (chrome & safari)
http://jsbin.com/kasovom/edit?html,output

@valdrinkoshi 
Your code less import "paper-header-panel/paper-header-panel.html", so could not reproduce.

**Comment by valdrinkoshi** [comment]
@MarxTseng this is caused by how the stacking context works.
`paper-header-panel` sets [`-webkit-overflow-scrolling: touch`](https://developer.mozilla.org/en-US/docs/Web/CSS/-webkit-overflow-scrolling) for smoother scrolling on ios, but that creates a new stacking context, and all elements within it will be "trapped" inside it. The backdrop is added on `document.body`, so it renders on top of the `paper-header-panel` and whatever is trapped inside it.

Please see more details [in this other issue](https://github.com/PolymerElements/paper-dialog/issues/44#issuecomment-172013206).

**Comment by marxtseng** [comment]
@valdrinkoshi  Thank you! I will try it.
