### ISSUE TITLE
tabindex behaving erratically inside a paper-dialog

### ISSUE THREAD

**Issue by Kilometers42** [PolymerElements/paper-dialog#61]
It seems like setting tabindex for elements inside a paper-dialog doesn't work. In the example below, in Chrome, when you tab through it goes W3Schools then Microsoft and never hits Google while in Internet Explorer it never tabs to any of them. Any ideas of what is causing this and how to fix it? Thanks!

```
<dom-module id="my-modal">
  <template>
    <button on-click="toggle">Test</button>
        <paper-dialog id="modal" modal>
        <a href="http://www.w3schools.com/" tabindex="2">W3Schools</a>
        <a href="http://www.google.com/" tabindex="1">Google</a>
        <a href="http://www.microsoft.com/" tabindex="3">Microsoft</a>
    </paper-dialog>
  </template>
  <script>
    (function () {
      'use strict';

      Polymer({
        is: 'my-modal',
        toggle: function(){
        this.$.modal.toggle();
        }
      });
    })();
  </script>

</dom-module>
```

**Comment by valdrinkoshi** [comment]
This is caused by `paper-dialog-behavior` setting the dialog's `tabindex` to -1 [here](https://github.com/PolymerElements/paper-dialog-behavior/blob/master/paper-dialog-behavior.html#L74). If we remove it, we can see the focus on all the elements while tabbing.
@cdata, any idea why this is happening? Shall we move this issue to `paper-dialog-behavior`?

**Comment by cdata** [comment]
Setting `tabindex="-1"` on the `paper-dialog` is intentional. I believe that the intent is for the dialog host not to be focusable via tabbing.

You can actually tab to the Google link, but you have to go in reverse tab order. I believe that the problem is that `IronOverlayBehavior` (or maybe nother behavior) is trying to find something focusable to focus and then focusing that thing. This might be disrupting the normal tab order.

Yeah, I think this issue needs to be moved. Maybe to `PaperDialogBehavior`, maybe to `IronOverlayBehavior`.

**Comment by valdrinkoshi** [comment]
The issue is on `PaperDialogBehavior` http://jsbin.com/nuwazas/7/edit?html,output

**Comment by valdrinkoshi** [comment]
This issue was moved to PolymerElements/paper-dialog-behavior#47
