### ISSUE TITLE
Continuous animations brake the dialog functionality

### ISSUE THREAD

**Issue by naoak** [PolymerElements/paper-dialog#77]
Double tapping the `TRANSITIONS` button in demo could brake dialog functionality.

![pd](https://cloud.githubusercontent.com/assets/1264530/11926072/f329dd76-a804-11e5-96bb-7c265748c2b6.gif)

I guess,
The first tap opens a dialog with entry animation(A).
Next, the second tap on backdrop closes the dialog with exit animation(B) and also on button opens another dialog with entry animation(C).

I think the animation (C) should be played after the animation (B) is canceled.

**Comment by naoak** [comment]
```
    _renderOpened: function() {
      if (this.withBackdrop) {
        this.backdropElement.open();
      }

      // inserted
      this.cancelAnimation();

      this.playAnimation('entry');
    },
    _renderClosed: function() {
      if (this.withBackdrop) {
        this.backdropElement.close();
      }

      // inserted
      this.cancelAnimation();

      this.playAnimation('exit');
    },
```

Inserting cancelAnimation()s before playAnimation()s fixes this issue except that backdrop is not shown.

**Comment by valdrinkoshi** [comment]
The `cancelAnimation` doesn't really solve the issue. The main problem is that with the double click, the computed `z-index` of the backdrop gets messed up. Notice how the buttons are still clickable when the dialog is opened:
![double-click](https://cloud.githubusercontent.com/assets/6173664/11942858/78203faa-a7ee-11e5-91bf-52308e02e8f5.gif)

as soon as we click the button again, it reproduces the error you noticed. The problem is in the calculation of `z-index` in here https://github.com/PolymerElements/iron-overlay-behavior/blob/master/iron-overlay-manager.html#L63
the computed style returns 0, while `current.style.zIndex` is 103. Will further investigate why..

**Comment by valdrinkoshi** [comment]
There is a missing call to `dialog.refit()` right after it gets closed, or before opening it.
This is solved by the PR https://github.com/PolymerElements/iron-overlay-behavior/pull/71
