### ISSUE TITLE
paper dialog hides behind backdrop, menu and toolbar in safari-ipad

### ISSUE THREAD

**Issue by srikkbhat** [PolymerElements/paper-dialog#79]
As title.

Goto http://www.oostnet.com/programs/manchester-ct and click on the `filter` icon

**Comment by valdrinkoshi** [comment]
Hi @srikkbhat, this issue is caused by the fact that `z-index`, even if calculated properly (the backdrop has 102, and the dialog 103), is not handled properly on safari. ~~You can see a similar example in this other issue #44~~ (not related)

After some investigation I discovered that the css property [`-webkit-overflow-scrolling: touch`](https://developer.mozilla.org/en-US/docs/Web/CSS/-webkit-overflow-scrolling) causes issues on the rendering of `z-index` (here the jsbin used in the test http://jsbin.com/nucixu/3/edit?html,output)
![webkit-overflow-scrolling](https://cloud.githubusercontent.com/assets/6173664/12114443/cf00b31a-b35e-11e5-9ab5-4a07fcd57522.gif)

@cdata @blasten FYI

**Comment by srikkbhat** [comment]
@valdrinkoshi Thanks for looking into this.  I assume including `z-index` for the 'paper-dialog` in my app is the fix for now.

**Comment by valdrinkoshi** [comment]
@srikkbhat I don't think that will solve the issue.
If you can afford it, put the dialogs outside the `paper-header-panel` (e.g. in `body`).

**Comment by valdrinkoshi** [comment]
@srikkbhat I confirm that this is due to how stacking context works.
All `paper-dialogs` with backdrop should be added in the same stacking context of `body` (because `iron-overlay-backdrop` is appended there).

See this example: http://jsbin.com/coxobi/2/edit?html,output
Here more details https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Positioning/Understanding_z_index/The_stacking_context

**Comment by nicholaswmin** [comment]
So, we basically can't use any `<paper-dialogs>` in [Polymer Starter kit](https://github.com/PolymerElements/polymer-starter-kit)? 
- Asking because _content_ is enclosed in a `<paper-scroll-header-panel>` by default there. Are there any workarounds for that?

**Comment by valdrinkoshi** [comment]
Unfortunately this is a limitation from the platform, [try it yourself](http://jsbin.com/lemufe/4/edit?html,output).

Even if the backdrop would be a sibling of the dialog (and not hide it), the stacking context of the parent would influence scrolling or cropping ([see example](http://jsbin.com/xoheka/2/edit?html,output)).

So the workaround for now is to ensure your `paper-dialog`s are declared in `body` (so they share the `body`'s stacking context).

Hope it helps..!

**Comment by nicholaswmin** [comment]
Hm, what if the element appended the `overlay` on `<body>` irregardless of the `paper-dialog` placement? 

Wouldn't that be a viable workaround? Or is it a no-no because it mandates accessing DOM outside of an element's ShadowDOM/scope?

**Comment by valdrinkoshi** [comment]
We're working on `overlays 2.0` to make it easier to deal with stacking context issues, most likely it will be a new element.

For now reparenting is one option, but watch out for styles & to have a reference of the dialog inside your element. 

Another option is to just declare the dialogs in `body` or a `dialog-container` element, & access to your dialog by querying `Polymer.dom(document).querySelector('dialog-container #myDialog')`.

**Comment by jamesmgg** [comment]
I'm still having an issue with this... are there any work arounds?

**Comment by valdrinkoshi** [comment]
Hi @jamesmgg, for now the suggestion is to declare the `paper-dialog` in a stacking-context-safe node, e.g. `document.body` (or at least outside the node that is creating a new stacking context)

**Comment by ppalladino** [comment]
Having this problem too. Putting all dialogs in body is not a solution. C'mon!

**Comment by valdrinkoshi** [comment]
@ppalladino this is a limitation of overlays in general, any node that creates a new stacking context will trap all the content within it, dialogs included. The only escape to the stacking context trap is not falling into the trap  `¯\_(ツ)_/¯`
If you find a solution on how to make the button clickable and the overlay render on top of the backdrop please let me know :) http://jsbin.com/cecuqiviye/1/edit?html,output

I've created a codelab to explain the issues in building custom overlays https://codelabs.developers.google.com/codelabs/building-custom-overlays/
In there I propose a different approach on how to escape the stacking context trap consisting in lazily stamping the content and hosting it in a stacking-context-safe node; I'm working on an element that does that for you, https://github.com/PolymerLabs/iron-overlay, but it has other problems like you loose styles scoping, and the details of your inner element leak outside its shadow dom (as content gets stamped in another node).

**Comment by ppalladino** [comment]
@valdrinkoshi I apologize for the snarky post. I discovered this issue a day before a demo and commented out of frustration. I do understand the problem and appreciate you taking the time to respond. Friends? :innocent:

**Comment by valdrinkoshi** [comment]
@ppalladino friends as before 🍰 🎉 😄 
I understand, this is one of those ugly surprises that you don't want to discover a day before the demo!

**Comment by Sinjins** [comment]
@valdrinkoshi While I understand moving to Polymer 2.0+ may resolve this issue, if I (for the time being) stay with pre-2.0 paper-dialog, and utilize a dialog-container element that is implemented at the same level as the highest app-level element, what about the **_on-tap_** handlers for the dialog button actions?  Normally, one would simply be able to define a function within the element that uses the dialog, such as '_**_next**_', and everything remains encapsulated inside the custom element, including the various dialogs that it needs.  Now, if I instead need to use a dialog-container element at the app level, what is the recommended approach to call a function on tap that remains inside the desired original element?  Do I now need to fire an iron-signal so that a deeply nested child element (or child of the sibling app-level element) can listen and react accordingly?  Needless to say, I don't think that is very desirable.

**Comment by valdrinkoshi** [comment]
@Sinjins some techniques to circumvent the issue are hiding the backdrop element singleton and set the `outline` property of the dialog, or to reparent the singleton to be into the opened dialog shadow root, but mileage may vary according to your DOM setup: e.g. see [this example](http://jsbin.com/sidevaj/3/edit?html,output), you won't be able to click the dialog buttons because dialogs are contained in an element that creates a new stacking context, `#left`, which takes 30% of the width, while `#right` takes the other 70% and is on top of `#left` in the stacking order.
You could reparent the dialog itself (e.g. `document.body.appendChild(this.$.dialog)`), but that would break the style encapsulation and query selectors like `this.$$('paper-dialog')`...

If you are in a situation like this, the only way out of the stacking context trap is to avoid it, e.g. define the dialogs in a stacking context safe node (e.g. `<body>`) and reference to them by id.

**Comment by BootsSiR** [comment]
I've been fighting with this issue for a few days.  I finally moved my dialogs out to the body and they are no longer hiding behind the backdrop.  However, my new issue is that if I try to scroll my dialog content on Safari the page behind the dialog scrolls :( I'm starting to feel like paper-dialog isn't really compatible with Safari and I should look for an alternative?  Or am I missing something in regards to the scrolling behaviour?

**Comment by valdrinkoshi** [comment]
@BootsSiR sorry you're finding these web platform limitations the hard way, but unfortunately there is no easy way to allow scrolling to happen only within a node (or at least, is not performant as we'd like).
This has already been requested [in here](https://github.com/PolymerElements/iron-overlay-behavior/issues/140), you'll find a solution you can use already ([in here](https://github.com/PolymerElements/iron-overlay-behavior/issues/140#issuecomment-210188361)). Hope that helps!

**Comment by BootsSiR** [comment]
Thanks @valdrinkoshi 

I ended up finding that solution you linked and it seems to be working for now.  It might be worth noting some of these issues in the element docs so people don't implement the elements and find out they are broken on iOS when it's too late.

**Comment by duykhoa** [comment]
I found [this answer](https://stackoverflow.com/a/37570263/1659807) on stackoverflow. It works for my case.

```js
openDialog: function(){
  var body = document.querySelector('body');
  Polymer.dom(body).appendChild(this.$.dialogId);
  this.$.dialogId.open();
}
```

**Comment by debkanchan** [comment]
@duykhoa YOU SAVED MY LIFE!!!
