### ISSUE TITLE
Disable auto close

### ISSUE THREAD

**Issue by tigerhawkvok** [PolymerElements/paper-dialog#8]
Buttons with a `onclick` event always close the dialog, and there's no way to prevent this from occurring. 

Like the 0.5 element, there should be a way to specify the close selector, or, at least, disable auto closing on buttons with a click event. 

If this is already available, it should be clearly documented (it isn't)

**Comment by morethanreal** [comment]
Do you have some example code where you encountered this issue? In a `<paper-dialog>` buttons with either the `dialog-confirm` or `dialog-dismiss` attribute close the dialog and they do nothing otherwise. You can see this in the dialog demo page in the "dialog with actions" demo. "Decline" and "accept" closes the dialog, but "more info" does not.

**Comment by tigerhawkvok** [comment]
Looks like I've debugged this down to my habit of returning `false` with my functions -- if a click event returns `false`, it closes the dialog (which is either undocumented or I didn't see it documented, in which case it's my fault)

See:

https://github.com/tigerhawkvok/paper-dialog-autoclose-bug / http://tigerhawkvok.github.io/paper-dialog-autoclose-bug/

**Comment by morethanreal** [comment]
I see, the dialog relies on the click event bubbling to the target to not close the dialog on click which is the cause of the issue.

**Comment by tigerhawkvok** [comment]
I can respect that. Probably should be documented, though, that returning false on a click event will close the dialog.
