### ISSUE TITLE
Call notifyResize when images within a dialog are loaded.

### ISSUE THREAD

**Issue by miztroh-zz** [PolymerElements/paper-dialog#86]
I often include images in my dialogs.  When paper-dialog opens, it resizes according to its content.  However, if one or more images haven't loaded yet, the resized dimensions aren't accurate.  It might make sense to listen for the `load` event and call `notifyResize`.

**Comment by valdrinkoshi** [comment]
@miztroh if you size already your images you won't face the problem
http://jsbin.com/wivadon/2/edit?html,output

`paper-dialog` implements the `iron-overlay-behavior` which observes the nodes and calls `notifyResize` when any of the node changes (here https://github.com/PolymerElements/iron-overlay-behavior/blob/master/iron-overlay-behavior.html#L349)

Maybe the image load should be considered as a node change...@cdata WDYT?

**Comment by miztroh-zz** [comment]
Definitely don't want to explicitly size the images due to responsive concerns.  Accounting for image loads in the overlay behavior would be awesome.

**Comment by valdrinkoshi** [comment]
Actually, the image load is not really changing the node.
I would suggest to handle it for the specific use case you have rather than having `iron-overlay-behavior` monitor its contents.
In this example we one `<img>` and carousel between some `src` http://jsbin.com/tokiku/4/edit?html,output
Notice that the `notifyResize` should not be triggered if we had setup `width` or `height` to the `paper-dialog` or the `img` (that's also why it makes it hard for `iron-overlay-behavior` to check for all these cases).

I think [`iron-image`](https://github.com/PolymerElements/iron-image) should implement `iron-resizable-behavior` so that it can call `notifyResize` once is loaded, something like this http://jsbin.com/rufifi/4/edit?html,output

**Comment by miztroh-zz** [comment]
@valdrinkoshi Good point.  However, your example doesn't seem to work with a narrow / mobile viewport.  Images exceed the bounds of the dialog.

**Comment by valdrinkoshi** [comment]
@miztroh nothing that some css can't solve :)
http://jsbin.com/rufifi/4/edit?html,output
Updated also previous comment's link

**Comment by valdrinkoshi** [comment]
I've created an issue here https://github.com/PolymerElements/iron-image/issues/62
Closing this one.

**Comment by valdrinkoshi** [comment]
@miztroh here's a better version (dialog stays always centered, also during the loading of the next image)
http://jsbin.com/rufifi/11/edit?html,output

**Comment by miztroh-zz** [comment]
@valdrinkoshi I noticed that in short viewport scenarios, the images protrude outside the bottom of the dialog.  To work around this, I thought to use a paper-dialog-scrollable.  However, that seems to break the whole thing.

http://jsbin.com/wujuxukatu/edit?html,output

**Comment by valdrinkoshi** [comment]
That's related to a bug of `paper-dialog-scrollable` that has been already fixed and available on master.
It works if you use the master version of `paper-dialog-scrollable` http://jsbin.com/nemoqu/1/edit?html
